### ISSUE TITLE
Remember move target dir durin program run

### ISSUE THREAD

**Issue by xmw** [gentoo/pornview#2]
It would be nice to return to the previous "move to" location during an programm run.
There's an HOME button to easily return to ~, so caching complicated selected paths like /home/images/cache/jpegchip/2013/... would be very handy.

Thanks

**Comment by hasufell** [comment]
a home button 7927c8edc76843df1f43232f1976ad094ca1daaa ?

**Comment by hasufell** [comment]
so you want to go into a subdir like

/home/xmw/.hidden-porn/all-the-hard-stuff/.no-one-should-ever-know-this-dir

then hit the home-button and be able to get back to that dir above?

**Comment by hasufell** [comment]
maybe this fixes it?
