### ISSUE TITLE
building fails with automake-1.13

### ISSUE THREAD

**Issue by t4c** [gentoo/pornview#3]
building pornview fails:

configure.ac:30: error: 'AM_PROG_CC_STDC': this macro is obsolete.
    You should simply use the 'AC_PROG_CC' macro instead.
    Also, your code should no longer depend upon 'am_cv_prog_cc_stdc',
    but upon 'ac_cv_prog_cc_stdc'.
/usr/share/aclocal-1.13/obsolete-err.m4:17: AM_PROG_CC_STDC is expanded from...
configure.ac:30: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
./autogen.sh  1.80s user 0.07s system 31% cpu 5.993 total

for a complete log see: http://nopaste.info/1198cf3f11.html

**Comment by hasufell** [comment]
fixed in c1263f8be64348ab911e6de9f547810f338cf841
